### ISSUE TITLE
Refactor - PDF builder object for ReportService

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#107]

**Comment by junweilam** [comment]
Start Date: 02/03/2023
End Date: 13/03/2023

**Preconditions**
- NIL

**Definitions of done: **
- Builder able to build PDF report

- [x] Able to build report
- [x] Feature able to work 
- [x] Data downloaded is accurate

**Example of created a builder with iText**


![Image](https://user-images.githubusercontent.com/91267859/224631183-8af84f4e-62bb-4d0d-a1d7-3070258d40ce.png)


**Usage of builder in the Service**


![Image](https://user-images.githubusercontent.com/91267859/224631345-aa95682d-4fad-48c3-b59d-d344707b5f45.png)
