### ISSUE TITLE
Refactor - Refactor DTO Factory for notification

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#109]
## Refactor DTO Factory for notification
Do the work on `refactor/notification-dto-factory` branch

Start Date: 09/03/2023
End Date: - 

### Preconditions:
- None

### Definition of done:
- [x] Completed refactor of notification DTOs to DTO factory
- [x] Pull request completed into `team 5` branch
- [x] No errors while compiling file

**Comment by rawsashimi1604** [comment]
created branch for Edmund


![Image](https://user-images.githubusercontent.com/75880261/224047941-85b605c7-0f17-4e8f-9a61-0e124f0a1307.png)

**Comment by rawsashimi1604** [comment]
changed design
![Image](https://user-images.githubusercontent.com/75880261/224069842-30adb381-9efb-4a3a-aea0-7f01ba7ebdb4.png)

**Comment by rawsashimi1604** [comment]
Completed factory refactor, Did not create abstract factory method for RequestDTO as .NET has auto mapping enabled


![Image](https://user-images.githubusercontent.com/75880261/224437819-ced4d093-b778-4fad-aba1-79157d692ef4.png)
![Image](https://user-images.githubusercontent.com/75880261/224437881-96ac394a-5aa1-4623-8442-051877917b22.png)
![Image](https://user-images.githubusercontent.com/75880261/224437935-5c51aea6-7184-41c4-a7fb-a591cefe8f43.png)

**Comment by 2102673** [comment]
![Image](https://user-images.githubusercontent.com/90232284/224495741-1c5cd4d0-f7e4-4f26-872a-8c8b76b5253d.png)



![Image](https://user-images.githubusercontent.com/90232284/224495808-67478f67-5a5c-48a0-b5f6-3ac51afe049a.png)

**Comment by rawsashimi1604** [comment]
Pull request completed into `team5` branch
