### ISSUE TITLE
Class Diagram: Improvements with design patterns

### ISSUE THREAD

**Issue by ChenYJ-SIT** [rawsashimi1604/ICT2106_P2_Project_M2#120]
Improve the class diagram with design patterns

**Comment by ChenYJ-SIT** [comment]
- Implementation of observer design pattern 

![Image](https://user-images.githubusercontent.com/90168655/224555770-02fdcd27-db33-489c-9fc4-2c8a67fa18e6.png)

(To be reviewed with prof during lab)

**Comment by rb-t** [comment]
Prof has accepted our design, we will be implementing the  SOLID principles and design patterns into the class diagram

**Comment by rb-t** [comment]
Implementation of  Factory pattern (Green classes)

![Image](https://user-images.githubusercontent.com/90168622/226127936-7c3d8e5e-b00e-493e-9610-07cf54369a14.png)

**Comment by rb-t** [comment]
Implementation after implemention patterns and SOLID principles

![Image](https://user-images.githubusercontent.com/90168622/226128167-0352faef-7668-4246-a906-9d39d848e40c.png)

**Comment by rb-t** [comment]
Done on 19/3/23
