### ISSUE TITLE
D2 Report Section 5: Detailed Design: Improvements made to class diagram

### ISSUE THREAD

**Issue by rb-t** [rawsashimi1604/ICT2106_P2_Project_M2#124]
Update of class diagram and description of SOLID principles used for detailed design should be reflected on D2 Report

Due 24 March

**Comment by rb-t** [comment]
Before Class Diagram: 

![Image](https://user-images.githubusercontent.com/90168622/225730635-daf9c34d-ef7a-4468-ab9c-fa73ce3856f4.png)

After Class Diagram: 

![Image](https://user-images.githubusercontent.com/90168622/225730876-57b622d3-b757-4e36-8c23-402715ffc886.png)

**Comment by ChenYJ-SIT** [comment]
update of class diagram to conform to ISP:

![Image](https://user-images.githubusercontent.com/90168655/227038612-2a8f12b8-ebf4-4361-bf27-9ad131a6b754.png)

To be done:
review to be done:
- component diag (lollipops provide to who if it is within the same component)
- dailyLog and weeklyLog from the factory pattern implementing the interfaces

**Comment by ChenYJ-SIT** [comment]
Update of class diagram to conform to DIP to be done
(reflected in code but not class diag)

DeviceLogService depends on IDeviceLogRepository:


![Image](https://user-images.githubusercontent.com/90168655/227042297-f97ed2c7-9e02-4ade-8984-02d46a7d03b8.png)

DeviceLogRepo implements IDeviceLogRepo:



![Image](https://user-images.githubusercontent.com/90168655/227044102-b7eff624-ca2f-4513-af8a-684b7680eee5.png)

**Comment by ChenYJ-SIT** [comment]
Update to the class diagram to conform to ISP (daily and weekly device logs created from factory implements the respective interface):

![Image](https://user-images.githubusercontent.com/90168655/227264996-9f91b088-349f-4eba-bb1b-398de02e881a.png)
