### ISSUE TITLE
D2 Report Section 1: Introduction

### ISSUE THREAD

**Issue by rylan98** [rawsashimi1604/ICT2106_P2_Project_M2#130]
- Describe ourproject and module
- Explain which part of the module our team is working on

**Comment by rb-t** [comment]
Included a uniflied glossary of abbrevations, terms and definitions

![Image](https://user-images.githubusercontent.com/90168622/229057387-7a1794df-fa03-4d2e-bbf8-0b1b889f5c88.png)

Done and closed on 31/3
