### ISSUE TITLE
D2 Report Section 2: Team’s Features and Requirements

### ISSUE THREAD

**Issue by rylan98** [rawsashimi1604/ICT2106_P2_Project_M2#131]
- List the user features our team is working on
- Status of completion of the feature (complete or incomplete)
- Task owner

**Comment by rb-t** [comment]
![Image](https://user-images.githubusercontent.com/90168622/229058463-5371628d-8d63-4b91-bbb0-92302182f98e.png)

Done and closed on 31/3
