### ISSUE TITLE
D2 - Team’s Features and Requirements

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#139]
## Complete Project Plan

Start Date: 26/03/2023
End Date: 30/03/2023

### Preconditions:
- None

### Definition of done:
- [x] List the user features your team is working on, status of completion of the feature (complete or incomplete), and owner. 
- [x] Highlight any changes from D1 (if any) eg. Feature dropped, feature changed etc

**Comment by rawsashimi1604** [comment]
Added table of requirements

![Image](https://user-images.githubusercontent.com/75880261/227771723-90c2dda3-ce58-4eb2-8bfe-bed40d51c69b.png)

**Comment by junweilam** [comment]
Reports for household and device completed

**Comment by jianweiiii** [comment]
aggregated view of analytics on the dashboard done

**Comment by 2102673** [comment]
Energy Efficiency completed

**Comment by Christabellet** [comment]
Carbonfootprint completed
