### ISSUE TITLE
D2 - Final Prototype

### ISSUE THREAD

**Issue by junweilam** [rawsashimi1604/ICT2106_P2_Project_M2#14]
## Complete Final Prototype

Start Date: 16/02//2023
End Date: 26/03/2023

### Preconditions:
- None

### Definition of done:
- [x] All user interface 
- [x] All system function 
- [x] Files able to compile without error

**Comment by junweilam** [comment]
**REPORT**



![Image](https://user-images.githubusercontent.com/91267859/228892695-8615e8de-5460-42b8-a354-ab7547373369.png)




![Image](https://user-images.githubusercontent.com/91267859/228892812-3c87c0f1-ab9d-4199-9410-3e23835660bc.png)

**Comment by jianweiiii** [comment]
Aggregated view of analytics on dashboard

![Image](https://user-images.githubusercontent.com/91450271/228892939-39463113-390c-4805-8c6d-02015120f0ea.png)

**Comment by nicnathaniel** [comment]
Forecast for energy usage and cost

![Image](https://user-images.githubusercontent.com/94159228/228893062-8a7039e5-bfd9-4dd1-8487-b84f8441ef5d.png)

**Comment by 2102673** [comment]
![Image](https://user-images.githubusercontent.com/90232284/228914956-c163566b-cea3-4e96-a536-10882940c520.png)

**Comment by Christabellet** [comment]
Carbonfootprint

![Image](https://user-images.githubusercontent.com/94042374/229102868-fac97c2e-e042-4228-a4c2-d03ea8fba2d2.png)
