### ISSUE TITLE
D2 Report Section 5: Design Pattern

### ISSUE THREAD

**Issue by minXnub** [rawsashimi1604/ICT2106_P2_Project_M2#147]
To include explanation on the 2 chosen design pattern - Factory & Observer
5.1 - Design Pattern - Factory
5.2 - Design Pattern - Observer

**Comment by minXnub** [comment]
Completed 5.1 Design Pattern - Factory

**Comment by geethika-m** [comment]
Completed 5.2 Observer pattern:
-Explanation for observer pattern
-Screenshots of observer pattern in class diagram

Completed on 30/3/2023
