### ISSUE TITLE
D2 Report Section 3: Team’s Module Design

### ISSUE THREAD

**Issue by minXnub** [rawsashimi1604/ICT2106_P2_Project_M2#148]

**Comment by minXnub** [comment]
Added screenshot and explanation on the component diagram

**Comment by geethika-m** [comment]
Added in explanation for the component diagram about our team providing IDeviceLoggingService for M1-T4 to allow them to use our methods to start logging when the device turns on, on 30/3/2023.

**Comment by rb-t** [comment]
Added table for components and their classes

![Image](https://user-images.githubusercontent.com/90168622/229088170-0e9b7159-e719-4248-9fec-93e9e5755da2.png)


Added explanation for component diagram and the required/provided interfaces

![Image](https://user-images.githubusercontent.com/90168622/229088284-81174530-2747-4901-b8bc-d6d4afe6b496.png)

**Comment by ChenYJ-SIT** [comment]
Class diagram:
- PDF included in submission file
![Image](https://user-images.githubusercontent.com/90168655/229089018-b720717d-d792-4905-8b2b-1531ed8e45b9.png)

Report writing:
![Image](https://user-images.githubusercontent.com/90168655/229088942-ddf3057f-b11c-4b60-9466-459084fc3ed8.png)

**Comment by ChenYJ-SIT** [comment]
Section completed on 31/03
