### ISSUE TITLE
D2 Report Section 6: Construction Design

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project_M2#149]
To do:

Add in explanations for construction design section before deadline on 31/3/2023.

**Comment by rb-t** [comment]
Made improvements to rylan's initial design


![Image](https://user-images.githubusercontent.com/90168622/229056108-e206bf9d-88c4-4498-8122-30247a8fe6ef.png)

Done and closed on 31/3
