### ISSUE TITLE
D2 Report Section 7: Screenshots of interfaces

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project_M2#150]
To do:

Add in 1 screenshot of UI for the feature the individual is in charge of.

Deadline: 31/3/2023

**Comment by geethika-m** [comment]
Added UI for set energy limit feature on 30/3/2023

![Image](https://user-images.githubusercontent.com/71939490/228757536-5f385adc-c3c2-496f-a761-f2a75787a419.png)

**Comment by rb-t** [comment]
UI for feature 5

![Image](https://user-images.githubusercontent.com/90168622/229058969-4c22df80-48fd-4c7e-b80f-ace4d2d219f1.png)

**Comment by ChenYJ-SIT** [comment]
UI for feature 4:

![Image](https://user-images.githubusercontent.com/90168655/229060436-82afd7e3-6620-49bb-9a5e-d786851e579b.png)

**Comment by rylan98** [comment]
UI for feature 3:

![Image](https://user-images.githubusercontent.com/97349748/229106179-93cefb7b-5851-4c79-b81c-e3ef00930ba6.jpg)

**Comment by ChenYJ-SIT** [comment]
Completed on 31/03
