### ISSUE TITLE
D2 - Reflections

### ISSUE THREAD

**Issue by junweilam** [rawsashimi1604/ICT2106_P2_Project_M2#152]
## Complete Working Prototype

Start Date: 30/3/2023
End Date:  30/3/2023

### Preconditions:
- None

### Definition of done:
- [x] Jun Wei Reflection Done
- [x] Christabelle Reflection Done
- [ ] Edmund Reflection Done
- [x] Gavin Reflection Done
- [x] Jian Wei Reflection Done
- [x] Nicholas Reflection Done

**Comment by junweilam** [comment]
![Image](https://user-images.githubusercontent.com/91267859/228889127-9cb5f170-6bc8-49c1-b3cf-fbce0ebee1ec.png)

Reflection Completed

**Comment by rawsashimi1604** [comment]
![Image](https://user-images.githubusercontent.com/75880261/228889193-d4b1fc90-3a46-4318-be0e-5e95ff4d24c7.png)

**Comment by nicnathaniel** [comment]
![Image](https://user-images.githubusercontent.com/94159228/228891594-a1068241-d5d3-44d5-a801-9e6325614693.png)

**Comment by 2102673** [comment]
![Image](https://user-images.githubusercontent.com/90232284/228924699-512f8cc0-a4f7-4655-9642-109d68d6b98e.png)
