### ISSUE TITLE
D2 - Create Team's Zipped Codes

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#153]
## Create Team's Zipped Codes

Start Date: -
End Date: -

From the `main` branch, create a zipped version of the team's codes which only contains our implementations...

here is a list of classes that belong to us, can be found in report as well...

<html>
<body>
<b style="font-weight:normal;" id="docs-internal-guid-cdf9f791-7fff-bd2c-db40-d15968acf63f"><div dir="ltr" style="margin-left:0pt;" align="left">

Component | Classes / Interfaces
-- | --
Notification | NotificationRepositoryINotificationRepositoryNotificationRecieveNotificationProxyReceiveNotificationServiceSendNotificationProxySendNotificationServiceIRecieveNotificationGetNotificationDTODataNotificationControllerNotificationDTOFactoryGetNotificationDTO AddNotificationDTOAddNotificationDTOData ISendNotification
Analytics | AnalysisControllerAnalysisDTOFactory
CarbonFootprint(Analytics sub-component) | CarbonFootprintRepositoryGetCarbonFootprintDTODataGetCarbonFootprintDTOCarbonFootprintICarbonFootprintRepositoryCarbonFootprintProxyCarbonFootprintServiceICarbonFootprint
Reports(Analytics sub-component) | PdfBuilderIPdfBuilderPdfFileReportServiceIReportReportProxyGetDevicesDTO GetDevicesDTOData GetHouseholdReportDTO GetDevicesReportDTO
Forecast(Analytics sub-component) | ForecastDataRepositoryForecastChartDataForecastServiceGetForecastChartDataDTO ForecastChartDataDTOData IForecastDataRepositoryForecastProxyIForecast
EnergyEfficiency(Analytics sub-component) | EnergyEfficiencyRepositoryEnergyEfficiencyEnergyEfficiencyServiceGetEnergyEfficiencyDTOGetEnergyEfficiencyDTODataIEnergyEfficiencyRepositoryEnergyEfficiencyProxyIEnergyEfficiencyAnalytics
Others (Common code not in the other components) | AbstractDTOFactoryRequestDTOIDTODataResponseDTOResponseInformationIEntity

</div></b>
</body>
</html>

### Preconditions:
- [x] refactor branch merged to main

### Definition of done:
- [x] Zip done from `main` branch

**Comment by jianweiiii** [comment]
Deleted all codes excluding codes that are done by us and have put it into a zip folder.
