### ISSUE TITLE
D2: Report Section 8: Reflection

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project_M2#155]
To do:
Add in individual reflections by 31/3/2023.

**Comment by ChenYJ-SIT** [comment]
Tick when completed:

- [x] Rubin

- [x] Geethika

- [x] Shu min

- [x] Rylan

- [x] Yan Jiun

**Comment by rb-t** [comment]
Done and closed on 31/3
