### ISSUE TITLE
D2 Retrospective

### ISSUE THREAD

**Issue by geethika-m** [rawsashimi1604/ICT2106_P2_Project_M2#156]
What we did well

What could be improved

What are the take away points

To be complete by 1 April 2023

**Comment by ChenYJ-SIT** [comment]
what went well:
- SOLID Principles and design patterns were well thought
- Managed to code full stack 
- Module Integration was smooth

What could be improved:
- work management could improve
- Communication is still an issue
- can be more prepared for the demo

Takeaway points:
- Take the initiative in your own work
- learn to communicate any issues encountered asap

**Comment by rb-t** [comment]
What went well:
- solid principles and design patterns helped make the code modular and was well implemented

What could be improved:
- members need to ask for help early if necessary, week 12 and 11 are busy weeks and tough to provide help then

Takeaway points:
- integrating to form a whole product is not easy as it is already tough to merge within the team let alone merging with other teams.
- many things have to be considered during the project and the planning has to be done concurrently while aligning with other teams

**Comment by minXnub** [comment]
**What we did well**

- able to complete the deliverable ahead of time

**What could be improved**

- communication within the team could be better
- start working on the features earlier
- seek help immediately when facing issue

**What are the take away points**

- start working on the features as early as possible
- its better to communicate in the team chat when facing issue/ changes is made to the project
- to not be afraid of asking as everyone is here to learn

**Comment by geethika-m** [comment]
What went well:
-Features were implemented before the final demo.

What could be improved:
-More regular communication amongst team members about project progress/updates/changes

Key takeaway points:
-Best to start earlier for the coding part.

**Comment by rylan98** [comment]
What went well:

- Most features aligned with what client require during demonstration
- Was able to implement both the feature's front and back end implementation

What could be improved:

- Individual responsibility in ensuring task completion

Takeaway points:

- Planning have to be done way more ahead, be it team or module level portion
