### ISSUE TITLE
Feature 4 - Log device activity and energy usage on device state change

### ISSUE THREAD

**Issue by rb-t** [rawsashimi1604/ICT2106_P2_Project_M2#68]
This feature works with module 1 to start the log when device turns on

A schedular is also required in this feature for automated updating of device usage, activity usage

**Comment by rb-t** [comment]
Domain layer codes 

DeviceLogWriteService.cs:

Updating Logs on state change

![Image](https://user-images.githubusercontent.com/90168622/218651097-f06ea969-8326-44a4-902d-f245357dcee2.png)

Inserting logs on device state On

![Image](https://user-images.githubusercontent.com/90168622/218651232-8606e8ce-0b5e-4d72-9282-9d0d2c6bc0e4.png)

**Comment by rb-t** [comment]
Data access layer codes

DeviceLogRepository.cs

Insert and Update methods

![Image](https://user-images.githubusercontent.com/90168622/218651464-17b3f7a6-5d6e-4d2f-b3bb-cfc3db8322b5.png)

**Comment by rb-t** [comment]
Still missing the schedular which triggeres the method hourly 

but the method to be called is created  in DeviceLogWriteService

![Image](https://user-images.githubusercontent.com/90168622/218651715-f4160811-da0e-4c1d-9158-c3b45c928685.png)

**Comment by ChenYJ-SIT** [comment]
Updated codes:

- DeviceLogWriteService.cs
UpdateDeviceLog


![Image](https://user-images.githubusercontent.com/90168655/224895824-a77e0e78-1fae-422e-b660-729c9cc89c72.png)

- DeviceLogRepo.cs
GetByDate


![Image](https://user-images.githubusercontent.com/90168655/224895928-64a23836-0579-4843-a492-62d468d4e62a.png)

- DeviceLogController
PutDeviceLog


![Image](https://user-images.githubusercontent.com/90168655/224896164-e6c340b0-25a3-4aa4-87ff-89e62524a738.png)

**Comment by ChenYJ-SIT** [comment]
Bugfix for not calling the update method inside UpdateDeviceLog:

- DeviceLogController:
PutDeviceLog


![Image](https://user-images.githubusercontent.com/90168655/224914446-396f9d4a-87d6-40aa-a423-adb4e850923a.png)

- DeviceLogWriteService:
UpdateDeviceLog


![Image](https://user-images.githubusercontent.com/90168655/224914671-ae8317b9-f597-4284-9cb2-ee5d80672b81.png)

**Comment by ChenYJ-SIT** [comment]
FrontEnd (changes and new additions):
- Frontend for device log now has tabs for the different features
- Device log 



![Image](https://user-images.githubusercontent.com/90168655/224915092-2ba5be23-ed14-4f86-b6fd-c5e64c9afaf6.png)

**Comment by rb-t** [comment]
Schedular which triggeres the method hourly

![Image](https://user-images.githubusercontent.com/90168622/228919751-41658aef-f726-4a8c-adb1-95add5b9d18c.png)

**Comment by rb-t** [comment]
Remaining with 'Fetching daily and weekly logs'

**Comment by ChenYJ-SIT** [comment]
Frontend update:


![Image](https://user-images.githubusercontent.com/90168655/228921791-234bcd83-3596-4ca3-bd54-f17f8b8ceb58.png)

Backend:

DeviceLogController.cs:

fetch weekly logs:


![Image](https://user-images.githubusercontent.com/90168655/228922370-3957f15c-b30d-4792-9eb6-d5274c607a17.png)

fetch daily logs:


![Image](https://user-images.githubusercontent.com/90168655/228922452-2f6d04cb-c249-4748-bd76-7729963d40fe.png)

Completed on 31/03
