### ISSUE TITLE
Feature 3 BackEnd - The user can choose to filter between the types of devices for comparison

### ISSUE THREAD

**Issue by rb-t** [rawsashimi1604/ICT2106_P2_Project_M2#69]
Domain and Data access layer  methods to pull the correct device Guid

**Comment by rylan98** [comment]
To fix several bugs

**Comment by rylan98** [comment]
![Image](https://user-images.githubusercontent.com/97349748/229079544-2bc8e073-554e-4cd9-9570-a6864eda9862.png)
![Image](https://user-images.githubusercontent.com/97349748/229079545-ec98ef9f-53ff-4e80-b148-7c6ab59fdeb3.png)

Able to pull backend Device Types as well as the list of devices of the selected type

Done on 24/03/2023
