### ISSUE TITLE
Feature 3 FrontEnd - The user can choose to filter between the types of devices for comparison

### ISSUE THREAD

**Issue by rb-t** [rawsashimi1604/ICT2106_P2_Project_M2#71]
Presentation Layer for filter between types of device for comparison

Controller - Uses the correct method to pull logs with the correct device type chosen

View - Allows user to choose what device type

**Comment by rylan98** [comment]
![Image](https://user-images.githubusercontent.com/97349748/229079422-bbe26099-f19a-4c7b-a1f0-e624592e2ff3.png)

Done on 14/03/2023
