### ISSUE TITLE
Feature 2 FrontEnd - Users are able to set energy usage/ spending limits and thresholds

### ISSUE THREAD

**Issue by rb-t** [rawsashimi1604/ICT2106_P2_Project_M2#74]
Presentation Layer for setting energy usage threshold

Controller - Uses the correct method to trigger notification when energy usage limit exceeds

View - Done by Module 2 team 6 for notication view

**Comment by geethika-m** [comment]
Presentation layer for setting and viewing energy usage limits for devices:

![Image](https://user-images.githubusercontent.com/71939490/227795499-a87cd02a-1995-4821-bcec-15b263c5c0ec.png)

**Comment by geethika-m** [comment]
Method and logic in DeviceEnergyLimitController.cs to trigger notifications when energy usage is exceeded.

![Image](https://user-images.githubusercontent.com/71939490/227861287-90a397c0-b763-425d-88ef-ec87d0286758.png)
