### ISSUE TITLE
Feature 2 BackEnd - Users are able to set energy usage/ spending limits and thresholds

### ISSUE THREAD

**Issue by rb-t** [rawsashimi1604/ICT2106_P2_Project_M2#75]
Domain and Data access layer methods 

1. Create energy usage entity with double data type
2. Write Domain methods forUpdate/Insert New energyusage (Nullable) entity
3. Create new  Data access methods to update energy usage limit entity
4.  Check for energy usage exceeding limit when recalculating energy usage for devices
5.  Use ISendNotification interface when energy limit exceeds

**Comment by geethika-m** [comment]
Completed
