### ISSUE TITLE
Feature - Users can export reports of each device and the overall household which provides an overview of energy consumption and cost in the form of a .pdf format

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#86]

**Comment by junweilam** [comment]
Start Date: 02/03/2023
End Date: 13/03/2023

**Preconditions**
- Datasets for devices and device logs must be in the database

**Definitions of done: **
- PDF downloaded 

- [x] Able to connect to database
- [x] Feature able to work 
- [x] Data downloaded is accurate
