### ISSUE TITLE
Feature - Users are able to view forecasts of energy usage and cost for the week/month

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#87]
Start Date: 28/02/2023
End Date: 

**Preconditions**
- Database must be set up

**Definitions of done: **

- [x] ForecastRepository implemented
- [x] ForecastService created
- [x] Able to connect to database
- [x] Feature able to work 
- [x] Merged to team5 branch

**Comment by nicnathaniel** [comment]
reportRepository implemented along with IReportRepository

![Image](https://user-images.githubusercontent.com/94159228/222681488-bef88fdc-f043-4c29-84eb-f27a5bffcffb.png)

**Comment by nicnathaniel** [comment]
Start Date: 28/02/2023
End Date: 

**Preconditions**
- Database must be set up

**Definitions of done: **

- [] ForecastRepository implemented
- [] ForecastService created
- [] Able to connect to database
- [] Feature able to work

**Comment by nicnathaniel** [comment]
![Image](https://user-images.githubusercontent.com/94159228/227215838-610f598b-1ee3-488d-beaf-9ea9d0980c12.png)

Forecast Service

**Comment by rawsashimi1604** [comment]
![Image](https://user-images.githubusercontent.com/75880261/227713420-4b6dcfe8-ca4e-4bce-ba01-efa41979c202.png)


Added proxy implementation
