### ISSUE TITLE
Feature - Users are able to analyze device energy efficiency based on energy/usage data.

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#88]
Start Date: 25/02/2023
End Date: 26/03/2023

**Preconditions**
- Database must be set up

**Definitions of done: **

- [x] EnergyEfficiencyRepository implemented
- [x] EnergyEfficiencyService created
- [x] Proxy Implemented
- [x] Able to connect to database
- [x] Feature able to work 
- [x] Frontend completed
- [x] Merged to team5 branch

**Comment by 2102673** [comment]
![Image](https://user-images.githubusercontent.com/90232284/227770501-e7dd7f12-8472-4204-a3fc-098d68a9e1e1.png)


![Image](https://user-images.githubusercontent.com/90232284/227770513-76a3072f-8ca1-40ee-9993-9381a4ef3023.png)


![Image](https://user-images.githubusercontent.com/90232284/227770542-9998aaee-1b0d-4ff2-8edc-3c21b02df23e.png)
