### ISSUE TITLE
Feature - Users are able to view an aggregated view of the analytics on the dashboard.

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#89]
## Complete aggregated view of the analytics on the dashboard.

Start Date: 24/03/2023
End Date: 28/03/2023

### Preconditions:
- None

### Definition of done:
- [x] able to view the summary of all analytics

**Comment by jianweiiii** [comment]
![Image](https://user-images.githubusercontent.com/91450271/227923915-69d4b3a3-0fb6-4df4-8bd1-702e1df45082.png)

**Comment by jianweiiii** [comment]
![Image](https://user-images.githubusercontent.com/91450271/227924266-331656e6-1905-4b98-846c-bf6f9834c716.png)

**Comment by jianweiiii** [comment]
![Image](https://user-images.githubusercontent.com/91450271/227924389-78d1bf2c-27a3-4fe9-b50f-5f1a4fb42581.png)
