### ISSUE TITLE
Chore - refactor account service

### ISSUE THREAD

**Issue by rawsashimi1604** [rawsashimi1604/ICT2106_P2_Project_M2#96]
Start Date: 03/03/2023
End Date: -

### Preconditions:
- None

### Definition of done:
- [x] Link existing notification code to AccountService
- [x] Remove mockaccountservice (from program.cs too)

**Comment by 2102673** [comment]
![Image](https://user-images.githubusercontent.com/90232284/222698314-0a67bbe8-cdab-4623-8682-fa569145b847.png)



![Image](https://user-images.githubusercontent.com/90232284/222698537-3f822f65-d0c3-4374-8e90-da7e87ab42f6.png)
